[package]
name = "status_message_advanced"
version = "0.0.1"
authors = ["Aha Labs <team@ahalabs.dev>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "4.0.0"
witgen = "0.12.0"

